# Generated by Django 4.0.4 on 2022-06-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kristal', '0002_profileseller_profilecustomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilecustomer',
            old_name='interested_in',
            new_name='interests',
        ),
    ]
