# Generated by Django 4.0.4 on 2022-06-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kristal', '0003_rename_interested_in_profilecustomer_interests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileCustomer',
        ),
    ]
