# Generated by Django 4.0.4 on 2022-06-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kristal', '0004_delete_profilecustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileSeller',
        ),
    ]
