# Generated by Django 4.0.4 on 2022-06-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecustomer',
            name='image',
            field=models.URLField(),
        ),
    ]
