# Generated by Django 4.0.4 on 2022-06-15 05:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_alter_profilecustomer_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileCustomer',
            new_name='Customer',
        ),
    ]
