# Generated by Django 4.0.4 on 2022-06-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileseller',
            name='image',
            field=models.URLField(),
        ),
    ]
