# Generated by Django 4.0.4 on 2022-06-15 05:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0005_alter_comment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellers', '0002_alter_profileseller_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileSeller',
            new_name='Seller',
        ),
    ]
