# Generated by Django 4.0.4 on 2022-06-15 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_rename_profilecustomer_customer'),
        ('horses', '0006_rename_profilehorse_horse'),
    ]

    operations = [
        migrations.CreateModel(
            name='auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upate_price', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('customer', models.ManyToManyField(to='customers.customer')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horses', to='horses.horse')),
            ],
        ),
    ]
