# Generated by Django 4.0.4 on 2022-06-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_upate_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
