# Generated by Django 4.0.4 on 2022-06-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileHorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('history', models.TextField(blank=True)),
                ('pedigree', models.CharField(blank=True, choices=[('Keheilan', 'Keheilan'), ('Seglawi', 'Seglawi'), ('Abeyan ', 'Abeyan '), ('Hamdani', 'Hamdani'), ('Hadban', 'Hadban')], max_length=200, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horses', to='sellers.profileseller')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='')),
                ('comment_daate', models.DateTimeField(auto_now=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_horse', to='horses.profilehorse')),
            ],
            options={
                'verbose_name': 'Comment_table',
                'ordering': ['-comment_daate'],
            },
        ),
    ]
