# Generated by Django 4.0.4 on 2022-06-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilehorse',
            name='create_daate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
