# Generated by Django 4.0.4 on 2022-06-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0002_profilehorse_create_daate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilehorse',
            name='image',
            field=models.URLField(),
        ),
    ]
