# Generated by Django 4.0.4 on 2022-06-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0003_alter_profilehorse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilehorse',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
