# Generated by Django 4.0.4 on 2022-06-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_rename_profileseller_seller'),
        ('horses', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileHorse',
            new_name='Horse',
        ),
    ]
